<?php
$slug=preg_replace('/[^a-z0-9-]/','',$_GET['slug']??'isletmeler');
$map=[
'restoranlar'=>'Restoranlar','kafeler'=>'Kafeler','kahvalti'=>'Kahvaltı Mekanları','balik-restoranlari'=>'Balık Restoranları','kebapcilar'=>'Kebapçılar','pastaneler'=>'Pastaneler','firinlar'=>'Fırınlar','barlar'=>'Barlar',
'dis-klinikleri'=>'Diş Klinikleri','dis-hekimleri'=>'Diş Hekimleri','doktorlar'=>'Doktorlar','eczaneler'=>'Eczaneler','hastaneler'=>'Hastaneler','psikologlar'=>'Psikologlar','fizyoterapistler'=>'Fizyoterapistler','diyetisyenler'=>'Diyetisyenler','veterinerler'=>'Veterinerler',
'emlakcilar'=>'Emlakçılar','emlak-danismanlari'=>'Emlak Danışmanları','insaat-firmalari'=>'İnşaat Firmaları','muteahhitler'=>'Müteahhitler','mimarlar'=>'Mimarlar','ic-mimarlar'=>'İç Mimarlar','tadilat-firmalari'=>'Tadilat Firmaları','site-yonetimleri'=>'Site Yönetimleri',
'arac-kiralama'=>'Araç Kiralama','oto-servisleri'=>'Oto Servisleri','oto-galeriler'=>'Oto Galerileri','oto-ekspertiz'=>'Oto Ekspertiz','oto-yikama'=>'Oto Yıkama','lastikciler'=>'Lastikçiler','cekiciler'=>'Çekiciler','taksiler'=>'Taksiler','transfer-firmalari'=>'Transfer Firmaları',
'oteller'=>'Oteller','apart-oteller'=>'Apart Oteller','pansiyonlar'=>'Pansiyonlar','seyahat-acenteleri'=>'Seyahat Acenteleri','tekne-turlari'=>'Tekne Turları','yat-kiralama'=>'Yat Kiralama','jeep-safari'=>'Jeep Safari','dalis-merkezleri'=>'Dalış Merkezleri','su-sporlari'=>'Su Sporları',
'kadin-kuaforleri'=>'Kadın Kuaförleri','erkek-berberleri'=>'Erkek Berberleri','guzellik-merkezleri'=>'Güzellik Merkezleri','spa-merkezleri'=>'Spa Merkezleri','hamamlar'=>'Hamamlar','masaj-salonlari'=>'Masaj Salonları','lazer-epilasyon'=>'Lazer Epilasyon','dovme-studyolari'=>'Dövme Stüdyoları',
'elektrikciler'=>'Elektrikçiler','tesisatcilar'=>'Tesisatçılar','klima-servisleri'=>'Klima Servisleri','beyaz-esya-servisleri'=>'Beyaz Eşya Servisleri','telefon-tamiri'=>'Telefon Tamiri','bilgisayar-tamiri'=>'Bilgisayar Tamiri','cilingirler'=>'Çilingirler','marangozlar'=>'Marangozlar','boyacilar'=>'Boyacılar','temizlik-sirketleri'=>'Temizlik Şirketleri','hali-yikama'=>'Halı Yıkama','ilaclama-firmalari'=>'İlaçlama Firmaları','nakliyat-firmalari'=>'Nakliyat Firmaları',
'avukatlar'=>'Avukatlar','hukuk-burolari'=>'Hukuk Büroları','mali-musavirler'=>'Mali Müşavirler','muhasebeciler'=>'Muhasebeciler','sigorta-acenteleri'=>'Sigorta Acenteleri','tercumanlar'=>'Tercümanlar','reklam-ajanslari'=>'Reklam Ajansları','web-tasarim'=>'Web Tasarım Firmaları','yazilim-sirketleri'=>'Yazılım Şirketleri','fotografcilar'=>'Fotoğrafçılar','matbaalar'=>'Matbaalar','kargo-firmalari'=>'Kargo Firmaları',
'marketler'=>'Marketler','giyim-magazalari'=>'Giyim Mağazaları','ayakkabi-magazalari'=>'Ayakkabı Mağazaları','canta-magazalari'=>'Çanta Mağazaları','kuyumcular'=>'Kuyumcular','parfumeriler'=>'Parfümeriler','kozmetik-magazalari'=>'Kozmetik Mağazaları','hediyelik-esya'=>'Hediyelik Eşya Mağazaları','elektronik-magazalari'=>'Elektronik Mağazaları','mobilya-magazalari'=>'Mobilya Mağazaları','yapi-marketler'=>'Yapı Marketler','pet-shoplar'=>'Pet Shoplar','cicekciler'=>'Çiçekçiler',
'anaokullari'=>'Anaokulları','ozel-okullar'=>'Özel Okullar','dil-okullari'=>'Dil Okulları','surucu-kurslari'=>'Sürücü Kursları','dershaneler'=>'Dershaneler','muzik-okullari'=>'Müzik Okulları','dans-okullari'=>'Dans Okulları','spor-okullari'=>'Spor Okulları',
'spor-salonlari'=>'Spor Salonları','fitness-merkezleri'=>'Fitness Merkezleri','pilates-studyolari'=>'Pilates Stüdyoları','yoga-studyolari'=>'Yoga Stüdyoları','tenis-kulupleri'=>'Tenis Kulüpleri','yuzme-havuzlari'=>'Yüzme Havuzları',
'bankalar'=>'Bankalar','doviz-burolari'=>'Döviz Büroları','atm'=>'ATM','noterler'=>'Noterler','kargo-subeleri'=>'Kargo Şubeleri'
];
$name=$map[$slug]??ucwords(str_replace('-',' ',$slug));
$title="Alanya $name | En Yakın $name - AlanyaNow";
$desc="Alanya'da $name arıyorsanız işletmeleri bölge, iletişim ve hizmet bilgileriyle AlanyaNow üzerinden keşfedin. Mahmutlar, Oba, Kestel, Konaklı ve Alanya Merkez seçenekleri.";
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?></title><meta name="description" content="<?=htmlspecialchars($desc)?>"><link rel="canonical" href="https://alanyanow.com/alanya-<?=htmlspecialchars($slug)?>.html"><style>:root{--navy:#073b72;--blue:#0d67b5;--orange:#ff8a00;--bg:#f5f9fd;--line:#dfebf4;--muted:#66788c}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:var(--bg);color:#102b47}a{text-decoration:none;color:inherit}.wrap{max-width:1120px;margin:auto;padding:0 22px}header{background:#fff;border-bottom:1px solid var(--line)}.nav{height:72px;display:flex;align-items:center;justify-content:space-between}.brand{font-size:29px;font-weight:900;color:var(--navy)}.brand span{color:var(--orange)}.hero{background:linear-gradient(135deg,#e3f4ff,#fff);padding:46px 0}.hero h1{font-size:42px;color:var(--navy);margin:0 0 10px}.hero p{color:#46627c;line-height:1.6;max-width:820px}.box{background:#fff;border:1px solid var(--line);border-radius:18px;padding:22px;margin:24px 0}.empty{padding:28px;text-align:center;background:#f8fbfe;border-radius:14px;color:var(--muted)}.btn{display:inline-block;background:var(--orange);color:#fff;padding:12px 16px;border-radius:11px;font-weight:800}.links{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.links a{background:#eef7ff;color:var(--blue);padding:12px;border-radius:10px;font-weight:800}@media(max-width:700px){.hero h1{font-size:34px}.links{grid-template-columns:1fr}}</style></head><body><header><div class="wrap nav"><a class="brand" href="/">Alanya<span>Now</span></a><a href="/tum-sektorler.html">Tüm Kategoriler</a></div></header><section class="hero"><div class="wrap"><div style="font-size:13px;color:#66788c"><a href="/">AlanyaNow</a> › <a href="/tum-sektorler.html">Kategoriler</a> › <?=htmlspecialchars($name)?></div><h1>Alanya <?=htmlspecialchars($name)?></h1><p><?=htmlspecialchars($desc)?></p></div></section><main class="wrap"><div class="box"><h2>Alanya'daki <?=htmlspecialchars($name)?></h2><div class="empty">Bu kategorideki gerçek işletmeler Google ve yerel kaynaklardan ekleniyor. Liste kısa süre içinde dolacak.</div></div><div class="box"><h2>Bölgeye göre ara</h2><div class="links"><a href="#">Alanya Merkez <?=htmlspecialchars($name)?></a><a href="#">Mahmutlar <?=htmlspecialchars($name)?></a><a href="#">Oba <?=htmlspecialchars($name)?></a><a href="#">Kestel <?=htmlspecialchars($name)?></a><a href="#">Konaklı <?=htmlspecialchars($name)?></a><a href="#">Okurcalar <?=htmlspecialchars($name)?></a></div></div><div class="box"><h2>İşletmenizi ekleyin</h2><p>AlanyaNow lansman döneminde işletme kaydı ilk 3 ay ücretsizdir.</p><a class="btn" href="/?kayit=1">İşletmeni Ücretsiz Ekle</a></div></main></body></html>